# 01-PyBA:
## 20

#### 1. Set the variable `test1` to the string 'This is a test of the emergency text system,' and save test1 to a file named `test.txt`.

In [0]:
test1 = 'This is a test of the emergency text system.'
with open('test.txt', 'w') as file:
	file.write(test1)

#### 2. Read the contents of the file `test.txt` into the variable test2. Is there a difference between `test1` and `test2`?

In [0]:
with open('test.txt','r') as f:
	test2 = f.read()
print(test1==test2)

True

#### 3. Create a CSV file called `books.csv` by using these lines:
		title,author,year
		The Weirdstone of Brisingamen,Alan Garner,1960
		Perdido Street Station,China Miéville,2000
		Thud!,Terry Pratchett,2005
		The Spellman Files,Lisa Lutz,2007
		Small Gods,Terry Pratchett,1992

In [0]:
import csv

d = [
	['title', 'author', 'year'],
	['The Weirdstone of Brisingamen', 'Alan Garner', 1960],
	['Perdido Street Station', 'China Miéville', 2000],
	['Thud!', 'Terry Pratchett', 2005],
	['The Spellman Files', 'Lisa Lutz', 2007],
	['Small Gods', 'Terry Pratchett', 1992]]

with open('books.csv', 'w', newline='') as f:
	writer = csv.writer(f)
	writer.writerows(d)

#### 4. Use the `sqlite3` module to create a SQLite database called `books.db`, and a table called `books` with these fields: title (text), author (text), and year (integer).

In [0]:
import sqlite3

dbcon=sqlite3.connect('books.db');c=dbcon.cursor()
c.execute('''
	CREATE TABLE books(
		  title text, 
		  author text, 
		  year integer)
''')

#### 5. Read `books.csv` and insert its data into the `book` table.

In [0]:
with open('books.csv', 'r', newline='') as file:
	reader = csv.reader(file)
	next(reader)  # Skip header row
	c.executemany("INSERT INTO books VALUES (?, ?, ?)", reader)

In [0]:
dbcon.commit()

#### 6. Select and print the title `column` from the book table in alphabetical order.

In [0]:
c.execute("SELECT title FROM books ORDER BY title")
display(c.fetchall())

[('Perdido Street Station',),
 ('Small Gods',),
 ('The Spellman Files',),
 ('The Weirdstone of Brisingamen',),
 ('Thud!',)]

#### 7. From the `book` table, select and print all columns in the order of publication.

In [0]:
c.execute("SELECT * FROM books ORDER BY year")
display(c.fetchall())

[('The Weirdstone of Brisingamen', 'Alan Garner', 1960),
 ('Small Gods', 'Terry Pratchett', 1992),
 ('Perdido Street Station', 'China Miéville', 2000),
 ('Thud!', 'Terry Pratchett', 2005),
 ('The Spellman Files', 'Lisa Lutz', 2007)]

#### 8. Use the `sqlalchemy` module to connect to the sqlite3 database `books.db` that you just made in exercise 6.

In [0]:
from sqlalchemy import create_engine

engine = create_engine('sqlite:///books.db')
engine

Engine(sqlite:///books.db)

#### 9. Install the Redis server and the Python redis library (pip install redis) on your computer. Create a Redis hash called test with the fields count (1) and name ('Fester Bestertester'). Print all the fields for test.

In [0]:
import redis

r = redis.Redis()
r.hmset('test', {'count': 1, 'name': 'Fester Bestertester'})
print(r.hgetall('test'))

{b'count': b'1', b'name': b'Fester Bestertester'}

/tmp/ipykernel_74222/287400770.py:4: DeprecationWarning: Redis.hmset() is deprecated. Use Redis.hset() instead.
  r.hmset('test', {'count': 1, 'name': 'Fester Bestertester'})

#### 10. Increment the count field of test and print it.

In [0]:
r.hincrby('test', 'count', 1)
print(r.hget('test', 'count'))

b'2'